name       : haskell-http-download
version    : 0.1.0.1
release    : 1
source     :
    - https://hackage.haskell.org/package/http-download-0.1.0.1/http-download-0.1.0.1.tar.gz : 83244872d6f62c1e10c69ce0e87159649eefaf895e77cbdfa8f95287975730b8
license    : BSD-3-Clause
component  : programming.haskell
summary    : Verified downloads with retries
description: |
    Higher level HTTP download APIs include verification of content and retries
builddeps  :
    - haskell-base64-bytestring-devel
    - haskell-cabal-install
    - haskell-cryptonite-conduit-devel
    - haskell-http-conduit-devel
    - haskell-path-io-devel
    - haskell-retry-devel
    - haskell-rio-prettyprint-devel
rundeps    :
    - devel :
        - haskell-base64-bytestring-devel
        - haskell-cryptonite-conduit-devel
        - haskell-path-io-devel
        - haskell-http-conduit-devel
        - haskell-retry-devel
        - haskell-rio-prettyprint-devel
networking : yes
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
